### ISSUE TITLE
Error when using the children parameter in components

### ISSUE THREAD

**Issue by hibas123** [apiel/jsx-html#3]
Hi,

I had the following error, whenever I have a array of child elements. 

```
error: Uncaught TypeError: Cannot convert undefined or null to object
        normalizeChildren(child).forEach(result.push);
                                 ^
    at push (<anonymous>)
    at Array.forEach (<anonymous>)
    at normalizeChildren (normalizeChildren.ts:16:34)
    at ElementNode.renderChildren (Node.ts:14:26)
    at ElementNode.render (ElementNode.ts:27:31)
    at ComponentNode.renderComponent (ComponentNode.ts:32:32)
    at async ComponentNode.render (ComponentNode.ts:23:26)
```

The error can be reconstructed using the following code

```tsx
/// <reference path="https://raw.githubusercontent.com/apiel/jsx-html/latest/jsx.d.ts" />
import { React } from "https://raw.githubusercontent.com/apiel/jsx-html/latest/mod.ts";

function Test() {
   return (
      <div>
         {["1", "2", "3"].map((e) => (
            <div>{e}</div>
         ))}
      </div>
   );
}

(<Test />).render().then(console.log);

```
It seems to be a problem with the `normalizeChildren(child).forEach(result.push)` part in the `normalizeChildren.ts`. Changing it to `result.push(...normalizeChildren(child))` resolves it.

It doesn't matter if used with or without the --unstable flag.

My problem is it doesn't even work when using `normalizeChildren(child).forEach(result.push.bind(result)` which should resolve any potential this. issues.

**Environment:**

**OS:** Linux
**Deno:** 1.2.1
**v8:** 8.8.216

**Comment by apiel** [comment]
Are you sure about your issue? Cause I have a test case for it and it is passing: https://github.com/apiel/jsx-html/blob/master/examples/05.tsx

Also I tried your code an work for me on the last version. Are you using jsx-html 1.2.1 ?

**Comment by apiel** [comment]
Ah it seem you are using the tag latest, that is not up to date. I should remove this tag. Either use master to get the latest version or use a specific version.

**Comment by hibas123** [comment]
OK, yes using master this works now.
I should have tried that.

Thank you for your quick response.
