### ISSUE TITLE
Setting inner html

### ISSUE THREAD

**Issue by sdhoward** [apiel/jsx-html#4]
Hi, thanks for the great Deno module. Is there a mechanism available for this module, similar to [React's `dangerouslySetInnerHTML`](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml)? I am experimenting with dynamically generated markup and have other mechanisms for mitigating XSS risks (not using user input directly).

**Comment by apiel** [comment]
I don't have anything like this for the moment but I will try to implement it in the next days. Hopefully by end of the week...

**Comment by hibas123** [comment]
I was using `<div innerHTML={content} />`.

And it seems to work. Is that not intended?

**Comment by apiel** [comment]
You are right. Sorry, long time I implemented the lib and I forgot about it. I will update the doc.

**Comment by apiel** [comment]
doc updated in f3ab317

thx @hibas123
