### ISSUE TITLE
Error with empty div container

### ISSUE THREAD

**Issue by hibas123** [apiel/jsx-html#5]
Hello,

as I was testing today In noticed some strange behavior. It is complicated to describe, but when i have a empty div, the generated html contains something like `<div />`. This seems to be not working with browsers (tested in Firefox and Chrome) They don't recognize it as a open and close div, but instead only open without close. 

Running the example below will result in he following rendered layout.

![image](https://user-images.githubusercontent.com/19694792/89069819-32319a00-d374-11ea-8c73-de628c6f6a60.png)

```tsx
/// <reference path="https://raw.githubusercontent.com/apiel/jsx-html/master/jsx.d.ts" />
import {
   React,
   jsx,
   Fragment,
} from "https://raw.githubusercontent.com/apiel/jsx-html/master/mod.ts";

function Inner({ nr }: any) {
   return (
      <div style="margin-left: 1rem">
         <span>{nr}</span>
         <div>{""}</div>
      </div>
   );
}

function Root() {
   return (
      <html>
         <body>
            <div>
               {[1, 2, 3, 4, 5, 6].map((e) => (
                  <Inner nr={e} />
               ))}
            </div>
         </body>
      </html>
   );
}

(<Root />).render().then((res: string) => {
   Deno.writeFileSync("example.html", new TextEncoder().encode(res));
   console.log(res);
});
```
Other than in xhtml `<div />` seems to be invalid syntax and html5 recommends to not use self closing tags at all.

I will gladly create a pull request fixing this, but I would like to hear from you what you would do.

- Making a list of allowed tags for the /> syntax or generally disabling this behavior and instead always outputting html like `<img></img>`

**Environment:**

**OS:** Linux
**Deno:** 1.2.1
**v8:** 8.8.216

**Comment by apiel** [comment]
Amazing job, sound really great.

To tell you the story about jsx-html: I was actually first using https://github.com/krakenjs/jsx-pragmatic but there was so much bugs and the owner of the lib was not very responsive to PRs. Therefor I decide to re-work jsx-pragmatic under the name of jsx-html and focus on HTML rendering server side. I tried to solve several issue and introduce the asynchrone concept, but there is still lot small thing to improve. So I am really happy to get support, like your PR.

Feel free to propose any imporvement in the future ;-)

**Comment by apiel** [comment]
PR merged
