### ISSUE TITLE
pass container id as an argument for client side rendering

### ISSUE THREAD

**Issue by gutisalex** [apiel/jsx-html#7]
Hey, I am coming from jsx-pragmatic and wanted to try out your approach but I have a problem rendering stuff. 

### Problem Description

Using your example I am not getting anything rendered when adding this script to an html page. I also tried to use a div container with an id like you can do in jsx-pragmatic but I am not getting the container rendered anywhere?! So my question is how am I adding a `<div>Hello World</div>` container inside another div container with a certain id in a simple html page?

index.html

```
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>

    <script src="index.js"></script>

    <div id="div-container" />

    <script>
      zazmo.Test().render('#div-container').then((html) => {
        console.log(html);
      });
    </script>

  </body>
</html>
```

test.tsx
```
import { jsx, ElementNode } from 'async-jsx-html';

export function Test(props: any): ElementNode {
  console.log(props);
  return (
    <div>Hello World</div>
  )
}
```

tsconfig.json
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "module": "commonjs",
    "jsx": "react",
    "jsxFactory": "jsx",
    "esModuleInterop": true,
    "sourceMap": true,
    "allowJs": true,
    "lib": [
      "es6",
      "dom"
    ]
  }
}
```

### Workaround:

Change script in index.html to this: 
```
<script>
      zazmo.Test().render().then((html) => {
        console.log(html);
        const el = document.getElementById('div-container');
        el.innerHTML = html;
      });
    </script>
```

I could do this but it is not very well solved!

**Comment by apiel** [comment]
Are you using jsx-html in browser? I never tired this till now. I first implement it for Deno and then made it compatible to nodejs. What is `zazmo`:
```
zazmo.Test().render('#div-container').then((html) => {
        console.log(html);
      });
```
Right now I don't really see the link between jsx-html and your index.html file. I would need more details to help you. Do you maybe have a repository where I could look like?

**Comment by gutisalex** [comment]
Hey apiel, thx for your response!

Yes I am trying to use it in browser... I made a tiny ts lib where I import jsx-html and provide a function which returns a simple div container! A nice feature with jsx-pragmatic is that I can simply pass a string (id of the div container which I want to add the html to) with the render function and jsx-pragmatic will do the rest! I dont need to touch the DOM at all. Thats why I like the jsx approach overall, not having any to manipulate document myself! ;)

I made a gitlab rep you can clone and look into it: https://gitlab.com/gutisAlex/jsx2html.git

**Comment by apiel** [comment]
But in your repo, you don't instantiate `src/index.tsx`. You would need to do something like `(<Test />).render().then((html: string) => console.log(html));`

Have a look there: https://runkit.com/apiel/async-jsx-html-issues-7

**Comment by gutisalex** [comment]
I do this in the script tag in the index.html in the dist folder...

**Comment by apiel** [comment]
You might have forgot it in the repo because I cannot see any index.html, even if clone your repo and do `yarn build`

**Comment by gutisalex** [comment]
oh ya my bad I had /dist in .gitignore :) check it out now

**Comment by apiel** [comment]
Ok, you just have to change a small thing:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Page Title</title>
  </head>
  <body>

    <script src="index.js"></script>

    <div id="div-container" />

    <script>
      zazmo.Test().render().then((html) => {
        console.log(html);
        document.getElementById('div-container').innerHTML = html;
      });
    </script>

  </body>
</html>
```
Thanks for the example, I will re-use it to update the documentation ;-)

**Comment by gutisalex** [comment]
thats the workaround I have posted in my first post... but as I said, it would be much more elegant to use the render function and just pass the id of the div container you want to add the html to as an argument! 

Take a look at the paypal checkout integration for example (they use jsx-pragmatic): https://developer.paypal.com/docs/checkout/integrate/#3-render-the-smart-payment-buttons

As the maintainer of the website you just have to add the main script in your page and then call that function like that: 
```
<script>
    paypal.Buttons().render('#paypal-button-container');
    // This function displays Smart Payment Buttons on your web page.
</script>
```

**Comment by apiel** [comment]
Yes it look nice but `jsx-html` is first intented to render jsx on server side. Since you provided me some example to use it in frontend, I will also update the doc. Concerning `zazmo.Test().render('#div-container')`, it would mean that I make a special use-case for frontend. I like to keep the lib agnostic and therefor I am more in favour of keeping it as it is: `zazmo.Test().render().then((html) => { document.getElementById('div-container').innerHTML = html; });`

I will still think about but it would make the lib more complicated...
After, you could write a wrapper around, something like:
```ts
export async function jsxContainer(node: ElementNode, id: string) {
   const html = await node.render();
   document.getElementById(id).innerHTML = html;
}
```
In case you implement a nice wrapper, please share it with me, i wil then add it to the lib.

**Comment by apiel** [comment]
I was looking in the code of `jsx-pragmatic` and I can't find where they are doing this. Are you sure it is included inside? Isn't it a layer paypal put over `jsx-pragmatic`?

**Comment by gutisalex** [comment]
Hmm, I just took a look into their library and under /src there is a file called node.js! It includes a class called ElementNode! 
That call from the paypal api `paypal.Buttons()` is a function which returns such ElementNode! That ElementNode has a function called render() and here is all the vodoo.  It gets a bit dirty there with generics and some crazy stuff like <*, *> but as an argument they want a renderer. Those renderer you will find in /src/renderers. The one we are looking for must be the dom renderer. I think there is everything you need... There is also an html renderer which I think is for server side rendering!

I hope I could shine some light!

So far...

**Comment by apiel** [comment]
Yeah, but that the thing, in jsx-pragmatic they manipulate the dom directly when using the dom renderer. Or in jsx-html I wanted to only generate HTML. I removed all this concept of different type of renderer to simplify the code and to focus on HTML rendering. Making such thing would complicate a lot the code, where at the end using the callback function is not so complicated. Also using this callback function would allow you to use any kind of library to update the dom, either in pure vanillaJS or with jquery or...
I will keep it as it is -.- and close the issue. Thx for your sugestion and for the webpack example ;-)
